// Rules are created based on knowledge acquired from the link below
//https://plumbr.eu/uncategorized/most-popular-java-ee-servers-2016-edition
import com.javacodegeeks.drools.tasks.ApplicationServerTask
import com.javacodegeeks.drools.frameworks.Framework;


rule "Application server task, Tomcat rule" salience 1
when serverTask : ApplicationServerTask()
then
    Framework container = new Framework();
    container.setName("Tomcat");
    serverTask.setFramework(container);
    serverTask.setReason("The "+container.getName()+" is most popular web container (application server`s main component), very light, best performed and with good support");
 end

 rule "Application server task, GlassFish rule" salience 2
 when serverTask : ApplicationServerTask()
 then
    Framework container = new Framework();
    container.setName("JBoss");
    serverTask.setFramework(container);
    serverTask.setReason("The "+container.getName()+" is fully JavaEE application server and has well provided documentation");
  end